services:
  db:
    ports:
      - 90:5432 # 90 - внешний порт, 8080 - внутренний
    container_name: DatabaseContainer
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  auth-service:
    build: .
    container_name: AuthService
    ports:
      - 80:8080 # 80 - внешний порт, 8080 - внутренний
    environment:
      - SPRING_DATASOURCE_URL = jdbc:postgresql://DatabaseContainer:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin

